### ISSUE TITLE
Problem in nhibernate commandhandler

### ISSUE THREAD

**Issue by defyjoy** [sharparchitecture/Sharp-Architecture-Cookbook#2]
in wiki its shown tht the commandprocessor returns a value as 

 var results = this.commandProcessor.Process(command);

```
    if (results.Success)
    {
        return this.RedirectToAction(x => x.Index());
    }
```

  return View(viewModel);

but in case of  original posted commits it has only

this.commandProcessor.Process(command);
  return View(viewModel);

as a result its not saving the data and commit is not done to database. can you please tell if there is something wrong over here tht inspite of passing the entity through the commandhandler its not getting saved ? i might b noob cause complete new to this . but thts how i saw things did work out ... can you please clarify wht made this occur .....

thanks for helping this noob in advance

**Comment by DavidSSL** [comment]
This implementation is flawed. Instead of doing an "Update" operation, an "Insert" is being done. Just check your database and you'll see new entries.

**Comment by DavidSSL** [comment]
Upon further investigation, the reason why the Insert is not getting done is due to the fact that when the SaveOrUpdate is getting done, the addressRepository.Id is always 0. 

This is due to 2 reasons. First of all, when the data is sent to the front end, the addressId is not part of the posted data but part of the querystring. This is easily solved by getting the id from the querystring. 

However, even after doing that, there is a problem in:

```
    public void Handle(ChangeCustomerAddressCommand command)
    {
        var address = this.addressRepository.Get(command.Id);
        var newAddress = new Address
                             {
                                 AddressLine1 = command.AddressLine1,
                                 AddressLine2 = command.AddressLine2,
                                 City = command.City,
                                 StateProvince = command.StateProvince,
                                 PostalCode = command.PostalCode,
                                 ModifiedDate = command.ModifiedDate,
                                 CountryRegion = command.CountryRegion
                             };

        address = newAddress;
        this.addressRepository.SaveOrUpdate(address);
    }
```

The problem occurs after

address = new Address

because newAddress's Id is always 0.

**Comment by chrisrichards** [comment]
Fixed by commit: https://github.com/sharparchitecture/Sharp-Architecture-Cookbook/commit/4ddf648ca3c5ac8fb89cbbb0196c58ac1d543599
