### ISSUE TITLE
Repositories - MappingTest - Reposotory Test

### ISSUE THREAD

**Issue by lmorduhay** [sharparchitecture/Sharp-Architecture-Cookbook#5]
I have the latest release of cookbook, im confused about the lack of repositories implementation, repositories test, and mapping test.

What am i not watching? There irs another version of code with such an implementation? if not, how do yoy suggest to do this?

Cheers, Lucas

**Comment by seif** [comment]
I don't understand what you are looking for, if you look in
https://github.com/sharparchitecture/Sharp-Architecture-Cookbook/blob/master/Solutions/SharpArchCookbook.Tasks/ProductModelTasks.cs

You will see how we get the repository injected and used.

If you are looking for a class that implemented IRepository<> you wouldnt find it, because it isnt needed, queries are done in classes that get the data. e.g.:
https://github.com/sharparchitecture/Sharp-Architecture-Cookbook/blob/master/Solutions/SharpArchCookbook.Web.Mvc/Controllers/Queries/Products/ProductsForSaleQuery.cs
